-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_sale_order | Rule: valid_state | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('odoo_sale_order') }}
WHERE state NOT IN ('draft', 'sent', 'sale', 'done', 'cancel')
