-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_sale_order | Rule: no_negative_totals | Severity: WARNING
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('odoo_sale_order') }}
WHERE amount_total < 0 AND state != 'cancel'
