-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_res_partner | Rule: name_required | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('odoo_res_partner') }}
WHERE name IS NULL OR TRIM(name) = ''
