-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_product_product | Rule: barcode_unique_when_set | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('odoo_product_product') }}
WHERE barcode IS NOT NULL
