-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_res_partner | Rule: contact_has_parent | Severity: INFO
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'info'], severity='warn') }}

SELECT *
FROM {{ ref('odoo_res_partner') }}
WHERE is_company = false AND parent_id IS NULL AND customer_rank > 0
