-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_sale_order | Rule: confirmed_orders_have_date | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('odoo_sale_order') }}
WHERE state IN ('sale', 'done') AND date_order IS NULL
