-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_res_partner | Rule: company_has_vat | Severity: INFO
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'info'], severity='warn') }}

SELECT *
FROM {{ ref('odoo_res_partner') }}
WHERE is_company = true AND customer_rank > 0 AND (vat IS NULL OR TRIM(vat) = '')
