-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_sale_order | Rule: cancelled_not_invoiced | Severity: WARNING
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('odoo_sale_order') }}
WHERE state = 'cancel' AND invoice_status = 'invoiced'
