-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_product_product | Rule: positive_sale_price | Severity: WARNING
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('odoo_product_product') }}
WHERE sale_ok = true AND list_price <= 0
