-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_res_partner | Rule: email_format_valid | Severity: WARNING
-- Synced: 2026-03-10 10:49 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('odoo_res_partner') }}
WHERE email IS NOT NULL AND email != '' AND email NOT LIKE '%_@_%.__%'
