-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_sale_order | Rule: amount_total_consistency | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('odoo_sale_order') }}
WHERE ABS(amount_total - (amount_untaxed + amount_tax)) > 0.01
