-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_product_product | Rule: name_required | Severity: CRITICAL
-- Synced: 2026-03-10 10:49 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('odoo_product_product') }}
WHERE name IS NULL OR TRIM(name) = ''
