-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_product_product | Rule: cost_not_exceeds_sale | Severity: INFO
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'info'], severity='warn') }}

SELECT *
FROM {{ ref('odoo_product_product') }}
WHERE standard_price IS NOT NULL AND list_price > 0 AND standard_price > list_price * 2
