-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: odoo_product_product | Rule: no_negative_weight | Severity: WARNING
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('odoo_product_product') }}
WHERE weight IS NOT NULL AND weight < 0
