-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_lead | Rule: converted_has_date | Severity: WARNING
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('salesforce_lead') }}
WHERE is_converted = true AND converted_date IS NULL
