-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_lead | Rule: email_format_valid | Severity: WARNING
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('salesforce_lead') }}
WHERE email IS NOT NULL AND email NOT LIKE '%_@_%.__%'
