-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_opportunity | Rule: closed_opps_have_amount | Severity: WARNING
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('salesforce_opportunity') }}
WHERE is_closed = true AND is_won = true AND (amount IS NULL OR amount = 0)
