-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_lead | Rule: converted_has_account | Severity: WARNING
-- Synced: 2026-03-10 10:49 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('salesforce_lead') }}
WHERE is_converted = true AND converted_account_id IS NULL
