-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_opportunity | Rule: stage_name_required | Severity: CRITICAL
-- Synced: 2026-03-10 10:49 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('salesforce_opportunity') }}
WHERE stage_name IS NULL OR TRIM(stage_name) = ''
