-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_contact | Rule: account_id_format | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('salesforce_contact') }}
WHERE account_id IS NOT NULL AND LENGTH(account_id) != 18
