-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_contact | Rule: no_future_created_dates | Severity: WARNING
-- Synced: 2026-03-10 10:49 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('salesforce_contact') }}
WHERE created_date > CURRENT_TIMESTAMP
