-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_lead | Rule: no_negative_revenue | Severity: INFO
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'info'], severity='warn') }}

SELECT *
FROM {{ ref('salesforce_lead') }}
WHERE annual_revenue < 0
