-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_opportunity | Rule: no_negative_amount | Severity: WARNING
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('salesforce_opportunity') }}
WHERE amount < 0
