-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_opportunity | Rule: closed_won_consistency | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('salesforce_opportunity') }}
WHERE is_won = true AND is_closed = false
