-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_contact | Rule: last_name_required | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('salesforce_contact') }}
WHERE last_name IS NULL OR TRIM(last_name) = ''
