-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_account | Rule: no_null_account_names | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('salesforce_account') }}
WHERE name IS NULL OR TRIM(name) = ''
