-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: salesforce_account | Rule: modified_after_created | Severity: WARNING
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('salesforce_account') }}
WHERE last_modified_date < created_date
