-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_vbak | Rule: customer_not_null | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('sap_vbak') }}
WHERE kunnr IS NULL OR TRIM(kunnr) = ''
