-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_mara | Rule: material_type_required | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('sap_mara') }}
WHERE mtart IS NULL OR TRIM(mtart) = ''
