-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_mara | Rule: description_present | Severity: WARNING
-- Synced: 2026-03-10 10:49 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('sap_mara') }}
WHERE maktx IS NULL OR TRIM(maktx) = ''
