-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_mara | Rule: no_negative_weights | Severity: WARNING
-- Synced: 2026-03-10 10:49 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('sap_mara') }}
WHERE brgew < 0 OR ntgew < 0
