-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_mara | Rule: base_uom_required | Severity: CRITICAL
-- Synced: 2026-03-10 10:49 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('sap_mara') }}
WHERE meins IS NULL OR TRIM(meins) = ''
