-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_vbak | Rule: no_negative_net_value | Severity: WARNING
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('sap_vbak') }}
WHERE netwr < 0 AND auart NOT IN ('RE', 'CR')
