-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_kna1 | Rule: no_future_creation_dates | Severity: WARNING
-- Synced: 2026-03-10 10:49 UTC
-- Config: {{ config(tags=['datavow', 'warning'], severity='warn') }}

SELECT *
FROM {{ ref('sap_kna1') }}
WHERE erdat > CURRENT_DATE
