-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_vbak | Rule: vbeln_format | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('sap_vbak') }}
WHERE LENGTH(TRIM(vbeln)) = 0 OR LENGTH(vbeln) > 10
