-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_vbak | Rule: delivery_date_after_creation | Severity: INFO
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'info'], severity='warn') }}

SELECT *
FROM {{ ref('sap_vbak') }}
WHERE vdatu IS NOT NULL AND vdatu < erdat
