-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_kna1 | Rule: country_code_valid | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('sap_kna1') }}
WHERE land1 IS NULL OR LENGTH(TRIM(land1)) != 2
