-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_mara | Rule: matnr_not_empty | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('sap_mara') }}
WHERE matnr IS NULL OR TRIM(matnr) = ''
