-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_kna1 | Rule: deleted_customers_flagged | Severity: INFO
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'info'], severity='warn') }}

SELECT *
FROM {{ ref('sap_kna1') }}
WHERE loevm = 'X' AND sperr != 'X'
