-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_kna1 | Rule: kunnr_format | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('sap_kna1') }}
WHERE LENGTH(TRIM(kunnr)) = 0 OR LENGTH(kunnr) > 10
