-- Generated by DataVow — do not edit manually. Rerun: datavow dbt sync
-- Contract: sap_kna1 | Rule: name1_required | Severity: CRITICAL
-- Synced: 2026-03-10 12:18 UTC
-- Config: {{ config(tags=['datavow', 'critical'], severity='error') }}

SELECT *
FROM {{ ref('sap_kna1') }}
WHERE name1 IS NULL OR TRIM(name1) = ''
